### ISSUE TITLE
Gör så att newline ersätts med blanksteg i utf8_strip

### ISSUE THREAD

**Issue by Burgestrand** [Burgestrand/twitterskylt#13]

**Comment by antonsv** [comment]
Det fungerade bra, men det blir ju inte lika snyggt i koden när man har "ett svart får" i fältet

**Comment by Burgestrand** [comment]
:trollface:

Om du fixade det får du gärna stänga denne ticketen när du har pushat. Du kan göra det med committen också om du skriver orden “fixes #13” någonstans i commit-meddelandet. :)

**Comment by antonsv** [comment]
Okej, då överväger jag att stänga då ^^
