### ISSUE TITLE
Bugg i add_date 

### ISSUE THREAD

**Issue by andake** [Burgestrand/twitterskylt#14]
När tweeten är mindre eller lika med 16 tecken lägger add_date inte på nåt datum.

När tweeten är större än 16 tecken förstör add_date strängen och det blir lite random data.

**Comment by andake** [comment]
I programlogiksrapporten står det om "platshållarsträgen" som ska finnas i strängen efter justering.
Men någon sån finns inte i meddelandet när det kommer in i add_date().

Kan detta vara felet?

**Comment by JakobKallin** [comment]
Kan det vara s att den strng som skickas till add_date inte innehller
platshllaren "0123456789abc" i slutet? Funktionerna frlitar sig p att
den finns, s att ven datumet rknas med i justeringen av ord och inte
frstr ngon text. Funktionen add_date utgr frn att den finns med i
strngen, s om den saknas kan saker nog g fel.

Jakob

2012/4/13 andake <
reply@reply.github.com
