### ISSUE TITLE
Fel datumformat i convert_date

### ISSUE THREAD

**Issue by andake** [Burgestrand/twitterskylt#15]
convert_date() verkar basera sig på datumformatet: 
Sat Jan 12 23:34:45 +0000 2012

Men datumformatet från Twitters API är:
Fri, 13 Apr 2012 07:56:57 +0000

**Comment by JakobKallin** [comment]
Twitter anvnder sig tydligen av tv olika datumformat i sitt API: ett i
search och ett i resten. Jag ska skriva kod som ndrar till det srskilda
formatet i search.

Jakob

On Fri, Apr 13, 2012 at 12:23 PM, andake <
reply@reply.github.com
