### ISSUE TITLE
ÅÄÖ på displayen

### ISSUE THREAD

**Issue by JakobKallin** [Burgestrand/twitterskylt#16]
Jag såg i testerna att ÅÄÖ görs om till AAO när de körs genom utf8_strip. På den färdiga displayen vill vi om möjligt behålla just de tecknen som ÅÄÖ, men det får vi implementera när vi börjar jobba på displayen.

**Comment by Burgestrand** [comment]
Det stämmer. Beror lite på hur vår display representerar ÅÄÖ på bytenivå; förhoppningsvis är de bara en byte, typ latin-1 encoding vore schysst. Om de representeras av två bytes kommer det behövas göra lite större ändringar.

**Comment by ltidstam** [comment]
Displayen förväntar sig tecken som är en byte. Vi (jag och Anton) arbetar med tecken-kodningen på displayen nu.

**Comment by andake** [comment]
ÅÄÖ funkar nu.
