### ISSUE TITLE
Samverkan mellan HTTP och Parser

### ISSUE THREAD

**Issue by andake** [Burgestrand/twitterskylt#20]
Försökte idag får ihop kopplingen mellan HTTP och Parser idag. Vet inte om detta är en issue riktigt men stötte på lite
problem och ska försöka förklara dessa här.
# Kod

Fick modifiera den nuvarande TweetParser::parse() så att den tog in en buffer.

``` c
text = (char *) calloc(161, sizeof(char));
date = (char *) calloc(41, sizeof(char));
TweetParser *parser = new TweetParser(text, 161, date, 41);
httpClient = new HTTP(HTTP_BUFFER_SIZE);

while (!finished) {
        const char * buffer = httpClient->tick(&length);
    finished = parser->parse(buffer, length);
}
```

Det gick att parsa in datumet, men efter några iterationer så krashade arduinon
och startade om innan den fått hela JSON strängen.

HTTP och Parsning funkade när jag testade dem var för sig.

**Comment by Burgestrand** [comment]
Jag sitter med det just nu vid Arduinon. Fick äntligen HTTP-klienten att fungera ordentligt. Det knepiga nu är att lista ut när HTTP-svaret är komplett.

**Comment by andake** [comment]
Jaha, tyckte den fungerade bra hehe.

Parsen säger ju till när den har fått all data. Är det inte bara att avsluta då?

**Comment by Burgestrand** [comment]
Tidigare så gjorde den ett anrop med fel host, så alla svar man fick tillbaka var bara felmeddelanden och ingen JSON.

Jo, det kanske är enklast så, att lita på JSON-parsern. Det andra alternativet verkar vara att läsa av Content-Length-headern och det blir något knepigare :(

**Comment by andake** [comment]
Hm. Bör nog generalisera den nu. För tidzon-anropet ska ju gå till api.twitter.com medans tweet-anropet till search.twitter.com

**Comment by Burgestrand** [comment]
Ah, just det. Hmm. Kanske en parameter till konstruktorn? Jag får fixa det senare, måste gå hemåt nu.

**Comment by andake** [comment]
Ja eller i get() istället för en IP. Så kan EthernetClients DNS fixa ipet istället. Eller kunde de blocka?

**Comment by Burgestrand** [comment]
Mm, DNS-uppslagningar blockerade.

**Comment by JakobKallin** [comment]
Man vet när HTTP:n är skickad genom att anropa EthernetClient.connected(). Jag testade själv för ett tag sedan och det verkade fungera som väntat, vilket det också borde göra i och med att det går över TCP, som ju stänger uppkopplingen när den är klar.

Gör det egentligen särskilt mycket om DNS-uppslagningar blockerar? De bör väl inte ske särskilt ofta förutsatt att Arduino cachar svaret. Men om man behöver slå upp dem själv så går det med hjälp av Ethernet-biblioteket. Har inte koden här men det gick att anropa en metod på Ethernet om jag inte minns fel.

Att skicka in en buffer till parsern bör vara den lättaste ändringen utifrån den kodstruktur som vi har nu. Om man bara ser till att ta bort den buffer som skickas i konstruktorn och blir till instansvariabel så borde allt fungera likvärdigt.

**Comment by JakobKallin** [comment]
Ännu enklare än vad jag kom ihåg: getHostByName i DNS-klassen. Kolla här: https://github.com/arduino/Arduino/blob/master/libraries/Ethernet/Dns.h

**Comment by Burgestrand** [comment]
@JakobKallin Twitters server stängde _inte_ uppkopplingen när anropet är färdigt, och det finns inte heller något speciellt i TCP för att stänga uppkopplingen när en överföring är färdig (däremot finns det hjärtslagsanropen med jämna intervall för att se efter om uppkopplingen är aktiv, samt funktionalitet som säger till den andra änden att den ska stänga ner). 

Twitter verkade dock stänga uppkopplingen automatiskt efter (vad jag tror var) 30 sekunder. Vi kan låta uppkopplingen vara öppen så länge eftersom vi ändå inte får någon data under den tiden, förutsatt att twitter inte försöker svartlista oss om vi fortsätter med det. Det är inte precis god sed att låta uppkopplingen vara öppen när den inte behövs längre.

**Comment by JakobKallin** [comment]
Jag kom precis ihåg att jag skickade headern "Connection: close" när jag testade det. Det verkade fungera och själva syftet med den headern är att stänga ned uppkopplingen efter överföring så jag tror att vi kan använda den: "HTTP/1.1 defines the "close" connection option for the sender to signal that the connection will be closed after completion of the response."

**Comment by andake** [comment]
Skulle ha nån funktion, kanske HTTP->close() som kan använda EthernetClient::stop() (http://arduino.cc/en/Reference/ClientStop).
Så kan man anropa den när parsern är klar. För då behövs ju inte HTTP anslutningen längre.

**Comment by Burgestrand** [comment]
Använder destroy() istället, som i sin tur får anropa stop().
