### ISSUE TITLE
Fixa free för Parser-klasserna

### ISSUE THREAD

**Issue by JakobKallin** [Burgestrand/twitterskylt#22]
Vi behöver frigöra resurserna som Parser-klasserna använder (inklusive Yajl-grejerna) på något sätt, vare sig vi skapar ett nytt Parser-objekt för varje hämtning eller återanvänder samma.

**Comment by Burgestrand** [comment]
Låter bra. Jag glömde göra det i HTTP-klienten tidigare. Efter ungefär 80% av JSON-svaret på user/show.json så var arduinons minne fyllt och så dog den bara.

**Comment by andake** [comment]
Är det fixat i HTTP-klienten nu? Annars va det nog nåt sånt som hände när jag testade igår.
