### ISSUE TITLE
Formatting::format() klarar inte > 138 tecken

### ISSUE THREAD

**Issue by andake** [Burgestrand/twitterskylt#23]
@Burgestrand och @JakobKallin 
När jag testade med tweet längre än 138 tecken så klarade inte format() av sitt jobb.
Kändes som den gick utanför minnesutrymmet på nåt sätt. Meddelandet och tiden kom 
med, men det blev en massa blanksteg och nyradstecken emellan.

Dessa variabler skickades till format():

``` c
char * text = (char *) calloc(161, sizeof(char));
char * date = (char *) calloc(41, sizeof(char));
```

**Comment by Burgestrand** [comment]
Du råkar inte ha texten för originaltweeten och resultatet till hands?

**Comment by andake** [comment]
Tweet var:

```
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
```

Och resultatet från format() var nåt i stil med:
en del av meddelandet, sen massa blanksteg och nyrader
och avslutades med resten av meddelandet + datum

**Comment by andake** [comment]
Fungerade korrekt igår med tweetet:

```
dsfkldfsakljdsfadfsafkdkdafskladfskjdfsjkdafskkadsfkjadfskjkljdfakadfskjlkadjsflkjladsfjkadsfkjkjdafsjkadskjladsfkjkjladsfkjladsfkjladfsk140
```

Så förmodligen inget problem

**Comment by Burgestrand** [comment]
Alright, då stänger vi denne. Kommer problemet upp igen får vi fixa det.

**Comment by JakobKallin** [comment]
@andake Tog du den tweeten från Charlie Sheens konto? ;)

**Comment by andake** [comment]
Nej så galen är inte han. Det var @antonsv som gick loss på tagentbordet!

**Comment by antonsv** [comment]
@andake Haha, jag är värre än Charlie Sheen ^^ (OBS! jag var faktiskt nykter när jag skrev tweeten, till skillnad från vad Mr Winning brukar vara)
