### ISSUE TITLE
Säkerställa att tidszoner fungerar korrekt

### ISSUE THREAD

**Issue by JakobKallin** [Burgestrand/twitterskylt#26]
Just nu är tiderna i API:et två timmar bakom tiden som visas på displayen, vilket stämmer. UTC-offseten i användarinformationen på API:et är dock bara 3600, dvs. en timme. Om det är sommartid som orsakar tvåtimmarsskillnaden så vet jag inte var den faktiska extratimmen läggs till, för jag utgick från att det var UTC-offseten från API:et som räknade in den. Just nu fungerar det som sagt på rätt sätt men vi bör reda ut exakt vad som görs vad så att vi har full koll. Skulle vara pinsamt med en timmes fel på slutredovisningen.

**Comment by Burgestrand** [comment]
Som vi gick igenom via mail så fungerar dem korrekt. Har man en felaktig GMT-offset i användarens profil kommer tiden som visas på skylten att vara fel.
