### ISSUE TITLE
Inga tweets vid förfrågan leder till hängning.

### ISSUE THREAD

**Issue by antonsv** [Burgestrand/twitterskylt#30]
Vi arbetade med basstationen idag och märkte vi att om man kör en query som inte matchar några tweets så hamnar basstationen i någon form av oändlig loop när den försöker läsa in det senaste tweetet.

Ett sätt att framkalla felet är att hårdkoda in en query i sketchen såsom:

``` c
int8_t ret = httpClient->get(IPAddress(199,59,148,201), "/search.json", 6, "q", "from:exampleuserthatdoesnotexist", "result_type", "recent", "rpp", "1");
```

Output från serial monitor:

```

lets get
HTTP::get http_query: 
GET /search.json?q=from%3Aexampleuserthatdoesnotexist&result_type=recent&rpp=1 HTTP/1.1

HTTP_RECEIVING
AVAILABLE: 0

HTTP_RECEIVING
AVAILABLE: 0

(de senaste raderna upprepade några gånger)

HTTP_RECEIVING
AVAILABLE: 784

WILL READ: 200

RECEIVED: 200
HTTP/1.1 200 OK
Cache-Control: max-age=15, must-revalidate, max-age=300
Expires: Sun, 06 May 2012 17:56:00 GMT
Content-Type: application/json;charset=utf-8
X-Transaction: 1d460e69ef63c5d8
X-Frame
WAITING FOR BODY
HTTP::_read DONE
HTTP_RECEIVING
AVAILABLE: 584

WILL READ: 200

RECEIVED: 200
-Options: SAMEORIGIN
Content-Length: 286
Vary: Accept-Encoding
Date: Sun, 06 May 2012 17:51:00 GMT
X-Varnish: 1038203444
Age: 0
Via: 1.1 varnish
Set-Cookie: k=129.16.20.175.ae9e1ab6a406371d; pa
WAITING FOR BODY
HTTP::_read DONE
HTTP_RECEIVING
AVAILABLE: 384

WILL READ: 200

RECEIVED: 200
th=/; expires=Sun, 13-May-2012 17:50:59 UTC; domain=.search.twitter.com; httponly
Server: tfe

{"completed_in":0.167,"max_id":199194504249622529,"max_id_str":"199194504249622529","page":1,"query":"
WAITING FOR BODY
FOUND BODY
HTTP::_read DONE
HTTP_READING_BODY
AVAILABLE: 184

WILL READ: 184

RECEIVED: 184
from%3Aexampleuserthatdoesnotexist","refresh_url":"?since_id=199194504249622529&q=from%3Aexampleuserthatdoesnotexist","results":[],"results_per_page":1,"since_id":0,"since_id_str":"0"}
READING BODY
DONE READING
HTTP::_read DONE
HTTP_READING_BODY
AVAILABLE: 0

HTTP_READING_BODY
AVAILABLE: 0

HTTP_READING_BODY
AVAILABLE: 0

HTTP_READING_BODY
AVAILABLE: 0
```

Sedan fortsätter det att upprepas i all oändlighet. Förmodligen ligger någonting och försöker läsa data, vilket inte kommer att hända.

**Comment by andake** [comment]
Jo det är för att den loopen avslutas endast när YAJL har parsat in datumet + texten, vilket den inte kan göra i detta fall. 

``` c
while (!finished) {
        const char * buffer = httpClient->tick(&length);
        if (length > 0) {
            finished = parser.parse(buffer, strlen(buffer));
        }
    }
```

Alltså finished blir aldrig true.
Kanske borde fixas?

**Comment by andake** [comment]
Föreslår att man får har nån metod i HTTP lib som man kan kolla om TCP klienten är connected.
Om den inte är connected (all data mottagen) och parsningen inte är klar så är det förmodligen nåt fel.
Så nåt i stil med:

``` c
while (!finished && httpClient->is_connected())
```

Kanske?

**Comment by Burgestrand** [comment]
Har patchat HTTP-biblioteket att kolla om kopplingen är igång eller inte i unstable-branchen. Om twitter stänger ner kopplingen kommer HTTP-biblioteket att gå in i HTTP_DONE-state, som indikerar att inget mer kommer att parseas.

Vi kan fortfarande avsluta loopen när vi har parseat all data, men finished måste även sättas till true när httpClient->state() == HTTP_DONE.

**Comment by antonsv** [comment]
Vi testar Master och får från basstationen:

```

HTTP::_read DONE
HTTP_READING_BODY
AVAILABLE: 102

WILL READ: 102

RECEIVED: 102
e":true,"default_profile_image":true,"following":null,"follow_request_sent":null,"notifications":null}
READING BODY
DONE READING
HTTP::_read DONE
HTTP_READING_BODY
HTTP_DONE
HTTP_DONE
HTTP_DONE
HTTP_DONE
HTTP_DONE
HTTP_DONE
```

Det fastnar alltså innan den ens har hämtat in något att skicka till skylten. Innan har man kunnat skicka ett tweet iaf, vet dock inte om någon har ändrat i master efter det tyvärr.

**Comment by andake** [comment]
Okay.. Är det inga tweet då? Annars kan de va i setupTimezone L132
finished = parser.parse(read_data, read_length);
ska vara
finished = parser.parse(read_data, strlen(read_data));

**Comment by antonsv** [comment]
Vi kör unstable och när vi använder åäö så blir det fail det blir samma sak som mellanslag. Tolkas dock som skumma tecken. Tweetet är: Nån är hög

```

HTTP::_read DONE
HTTP_READING_BODY
AVAILABLE: 154

WILL READ: 128

RECEIVED: 128
"N\u00e5n \u00e4r h\u00f6g","to_user":null,"to_user_id":0,"to_user_id_str":"0","to_user_name":null}],"results_per_page":1,"since
READING BODY
DONE READING
HTTP::_read DONE
Mon, 14 May 2012 19:56:45 +0000
NÃ¥n Ã¤r hÃ¶g
Nn r hg
    - 14/5 21:56
loop
tweetTick(): nothing to do
loop
tweetTick(): nothing to do
loop
```

Utskrift på skylten är: N n  r h g    (plus datumet)

**Comment by andake** [comment]
Okej. åäö översätts ju till kodningen som fonten i skyltmodulen har.
Kanske är så att den displayen nu inte har samma kodning.

Så det blir väl att ändra i charmap[] @ Encoding.cpp isåfall.

**Comment by andake** [comment]
Eller kanske inte

**Comment by andake** [comment]
Misstänker nog att det är så ändå. Just HD44780:s teckentabell verkar ha plats för custom tecken där åäöÅÄÖ ligger (0x8X och 0x9X)

**Comment by Burgestrand** [comment]
Det som printas är UTF-8-enkodade tecken där de sammansatta tecknena tolkas som latin-1 (`Ã¶`). Det har troligtvis bara att göra med hur det visas, och betyder att datan som vi får in ser bra ut på bytenivå. Förutsatt att första byten är 0xC3 (`Ã` i latin-1) är det byte nummer två (`¶`) som bestämmer vad som slås upp i tabellen. Alla åäö och ÅÄÖ ligger högt upp i tabellen. Just ö verkar översättas till byte 0x94 i vårt fall. Om det stämmer på skylten eller inte vet jag inte.

**Comment by antonsv** [comment]
Vi ändrade översättningen så nu fungerar det hyfsat. Allt failar dock då tweeten är längre än 18 tecken, det blir en massa newline (200+) som skickas. Men eftersom att det endast är en provisorisk lösning så får vi helt enkelt låta bli att skriva längre än 18 tecken i morgon.
(vi är inte i labbet längre, så vi kan inte bifoga några utskrifter)
